# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BUILD_PUSH:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      # Runs a single command using the runners shell
      - name: Build Docker
        run: make build

      # Runs a set of commands using the runners shell
      - name: Push Docker
        run: |
          make push

  MINIKUBE:
    needs: [BUILD_PUSH]
    runs-on: ubuntu-latest
#     name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Modify the Tag
      working-directory: ./hello-world-chart
      run: sed -ri 's/\$TAG/'"$VERSION"'/' values.yaml
    - name: Deploy to minikube
      working-directory: ./hello-world-chart
      run: helm upgrade --install hello-world-chart .
#     - name: Build image
#       run: |
#         export SHELL=/bin/bash
#         eval $(minikube -p minikube docker-env)
#         docker build -f ./Dockerfile -t local/example .
#         echo -n "verifying images:"
#         docker images        
#     - name: Deploy to minikube
#       run:
#         kubectl apply -f deploy-to-minikube.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service hello-world-chart --url
        echo "------------------opening the service------------------"
        curl $(minikube service hello-world-chart --url)        
